// State to State - Laws Data
// Note: Data is simplified for educational purposes. Laws change frequently — always verify current status.

const STATES = {
  AL: { name: "Alabama",       region: "South" },
  AK: { name: "Alaska",        region: "West" },
  AZ: { name: "Arizona",       region: "Southwest" },
  AR: { name: "Arkansas",      region: "South" },
  CA: { name: "California",    region: "West" },
  CO: { name: "Colorado",      region: "Mountain" },
  CT: { name: "Connecticut",   region: "Northeast" },
  DE: { name: "Delaware",      region: "Northeast" },
  FL: { name: "Florida",       region: "South" },
  GA: { name: "Georgia",       region: "South" },
  HI: { name: "Hawaii",        region: "West" },
  ID: { name: "Idaho",         region: "Mountain" },
  IL: { name: "Illinois",      region: "Midwest" },
  IN: { name: "Indiana",       region: "Midwest" },
  IA: { name: "Iowa",          region: "Midwest" },
  KS: { name: "Kansas",        region: "Midwest" },
  KY: { name: "Kentucky",      region: "South" },
  LA: { name: "Louisiana",     region: "South" },
  ME: { name: "Maine",         region: "Northeast" },
  MD: { name: "Maryland",      region: "Northeast" },
  MA: { name: "Massachusetts", region: "Northeast" },
  MI: { name: "Michigan",      region: "Midwest" },
  MN: { name: "Minnesota",     region: "Midwest" },
  MS: { name: "Mississippi",   region: "South" },
  MO: { name: "Missouri",      region: "Midwest" },
  MT: { name: "Montana",       region: "Mountain" },
  NE: { name: "Nebraska",      region: "Midwest" },
  NV: { name: "Nevada",        region: "West" },
  NH: { name: "New Hampshire", region: "Northeast" },
  NJ: { name: "New Jersey",    region: "Northeast" },
  NM: { name: "New Mexico",    region: "Southwest" },
  NY: { name: "New York",      region: "Northeast" },
  NC: { name: "North Carolina",region: "South" },
  ND: { name: "North Dakota",  region: "Midwest" },
  OH: { name: "Ohio",          region: "Midwest" },
  OK: { name: "Oklahoma",      region: "South" },
  OR: { name: "Oregon",        region: "West" },
  PA: { name: "Pennsylvania",  region: "Northeast" },
  RI: { name: "Rhode Island",  region: "Northeast" },
  SC: { name: "South Carolina",region: "South" },
  SD: { name: "South Dakota",  region: "Midwest" },
  TN: { name: "Tennessee",     region: "South" },
  TX: { name: "Texas",         region: "South" },
  UT: { name: "Utah",          region: "Mountain" },
  VT: { name: "Vermont",       region: "Northeast" },
  VA: { name: "Virginia",      region: "South" },
  WA: { name: "Washington",    region: "West" },
  WV: { name: "West Virginia", region: "South" },
  WI: { name: "Wisconsin",     region: "Midwest" },
  WY: { name: "Wyoming",       region: "Mountain" },
  DC: { name: "Washington D.C.", region: "Northeast" },
};

// Value styling metadata
const VALUE_STYLES = {
  // Cannabis
  "Legal":            { color: "#22c55e", bg: "#14532d" },
  "Medical Only":     { color: "#f59e0b", bg: "#78350f" },
  "Illegal":          { color: "#ef4444", bg: "#7f1d1d" },
  // Death Penalty
  "Abolished":        { color: "#22c55e", bg: "#14532d" },
  "Moratorium":       { color: "#f59e0b", bg: "#78350f" },
  "Active":           { color: "#ef4444", bg: "#7f1d1d" },
  // Minimum Wage
  "Federal ($7.25)":  { color: "#ef4444", bg: "#7f1d1d" },
  "$8 – $11":         { color: "#f59e0b", bg: "#78350f" },
  "$12 – $14":        { color: "#60a5fa", bg: "#1e3a5f" },
  "$15+":             { color: "#22c55e", bg: "#14532d" },
  // Yes/No
  "Yes":              { color: "#22c55e", bg: "#14532d" },
  "No":               { color: "#94a3b8", bg: "#1e293b" },
  // Medicaid / ACA
  "Expanded":         { color: "#22c55e", bg: "#14532d" },
  "Not Expanded":     { color: "#ef4444", bg: "#7f1d1d" },
  // Abortion
  "Protected":        { color: "#22c55e", bg: "#14532d" },
  "Available / Limited": { color: "#f59e0b", bg: "#78350f" },
  "Severely Restricted": { color: "#f97316", bg: "#7c2d12" },
  "Banned":           { color: "#ef4444", bg: "#7f1d1d" },
  // Voter ID
  "None Required":    { color: "#22c55e", bg: "#14532d" },
  "Non-Strict ID":    { color: "#f59e0b", bg: "#78350f" },
  "Strict Photo ID":  { color: "#ef4444", bg: "#7f1d1d" },
  // Income Tax
  "None":             { color: "#22c55e", bg: "#14532d" },
  "Flat Rate":        { color: "#60a5fa", bg: "#1e3a5f" },
  "Graduated":        { color: "#f59e0b", bg: "#78350f" },
  // Carry
  "Permitless Carry": { color: "#f97316", bg: "#7c2d12" },
  "Permit Required":  { color: "#60a5fa", bg: "#1e3a5f" },
  // MAID
  "Authorized":       { color: "#22c55e", bg: "#14532d" },
  "Not Authorized":   { color: "#94a3b8", bg: "#1e293b" },
  // Sports Betting
  "Legal & Active":   { color: "#22c55e", bg: "#14532d" },
  "Legal / Pending":  { color: "#f59e0b", bg: "#78350f" },
  "Illegal":          { color: "#ef4444", bg: "#7f1d1d" },
};

function getValueStyle(val) {
  return VALUE_STYLES[val] || { color: "#94a3b8", bg: "#1e293b" };
}

const LAWS = [
  {
    id: "recreational_cannabis",
    category: "Cannabis",
    icon: "🌿",
    name: "Recreational Cannabis",
    description: "Legal status of recreational cannabis use for adults (21+)",
    source: "NCSL / Ballotpedia",
    stateValues: {
      AL: "Medical Only", AK: "Legal",      AZ: "Legal",      AR: "Medical Only",
      CA: "Legal",        CO: "Legal",      CT: "Legal",      DE: "Legal",
      FL: "Medical Only", GA: "Medical Only",HI: "Medical Only",ID: "Illegal",
      IL: "Legal",        IN: "Medical Only",IA: "Medical Only",KS: "Illegal",
      KY: "Medical Only", LA: "Medical Only",ME: "Legal",      MD: "Legal",
      MA: "Legal",        MI: "Legal",      MN: "Legal",      MS: "Medical Only",
      MO: "Legal",        MT: "Legal",      NE: "Medical Only",NV: "Legal",
      NH: "Medical Only", NJ: "Legal",      NM: "Legal",      NY: "Legal",
      NC: "Medical Only", ND: "Medical Only",OH: "Legal",      OK: "Medical Only",
      OR: "Legal",        PA: "Medical Only",RI: "Legal",      SC: "Illegal",
      SD: "Medical Only", TN: "Illegal",    TX: "Medical Only",UT: "Medical Only",
      VT: "Legal",        VA: "Legal",      WA: "Legal",      WV: "Medical Only",
      WI: "Medical Only", WY: "Illegal",    DC: "Legal",
    },
  },
  {
    id: "death_penalty",
    category: "Criminal Justice",
    icon: "⚖️",
    name: "Death Penalty",
    description: "Whether the state authorizes capital punishment",
    source: "Death Penalty Information Center",
    stateValues: {
      AL: "Active",     AK: "Abolished",  AZ: "Active",     AR: "Active",
      CA: "Moratorium", CO: "Abolished",  CT: "Abolished",  DE: "Abolished",
      FL: "Active",     GA: "Active",     HI: "Abolished",  ID: "Active",
      IL: "Abolished",  IN: "Active",     IA: "Abolished",  KS: "Active",
      KY: "Active",     LA: "Active",     ME: "Abolished",  MD: "Abolished",
      MA: "Abolished",  MI: "Abolished",  MN: "Abolished",  MS: "Active",
      MO: "Active",     MT: "Active",     NE: "Active",     NV: "Active",
      NH: "Abolished",  NJ: "Abolished",  NM: "Abolished",  NY: "Abolished",
      NC: "Active",     ND: "Abolished",  OH: "Moratorium", OK: "Active",
      OR: "Moratorium", PA: "Moratorium", RI: "Abolished",  SC: "Active",
      SD: "Active",     TN: "Active",     TX: "Active",     UT: "Active",
      VT: "Abolished",  VA: "Abolished",  WA: "Abolished",  WV: "Abolished",
      WI: "Abolished",  WY: "Active",     DC: "Abolished",
    },
  },
  {
    id: "minimum_wage",
    category: "Economic",
    icon: "💰",
    name: "Minimum Wage",
    description: "State minimum wage tier (as of 2024–2025)",
    source: "U.S. Department of Labor",
    stateValues: {
      AL: "Federal ($7.25)", AK: "$12 – $14",  AZ: "$12 – $14",  AR: "$12 – $14",
      CA: "$15+",            CO: "$12 – $14",  CT: "$15+",       DE: "$12 – $14",
      FL: "$12 – $14",       GA: "Federal ($7.25)", HI: "$12 – $14", ID: "Federal ($7.25)",
      IL: "$12 – $14",       IN: "Federal ($7.25)", IA: "Federal ($7.25)", KS: "Federal ($7.25)",
      KY: "Federal ($7.25)", LA: "Federal ($7.25)", ME: "$12 – $14", MD: "$15+",
      MA: "$15+",            MI: "$8 – $11",   MN: "$8 – $11",   MS: "Federal ($7.25)",
      MO: "$12 – $14",       MT: "$8 – $11",   NE: "$8 – $11",   NV: "$8 – $11",
      NH: "Federal ($7.25)", NJ: "$15+",       NM: "$12 – $14",  NY: "$15+",
      NC: "Federal ($7.25)", ND: "$8 – $11",   OH: "$8 – $11",   OK: "Federal ($7.25)",
      OR: "$12 – $14",       PA: "Federal ($7.25)", RI: "$12 – $14", SC: "Federal ($7.25)",
      SD: "$8 – $11",        TN: "Federal ($7.25)", TX: "Federal ($7.25)", UT: "Federal ($7.25)",
      VT: "$12 – $14",       VA: "$12 – $14",  WA: "$15+",       WV: "$8 – $11",
      WI: "Federal ($7.25)", WY: "Federal ($7.25)", DC: "$15+",
    },
  },
  {
    id: "constitutional_carry",
    category: "Gun Laws",
    icon: "🔫",
    name: "Constitutional / Permitless Carry",
    description: "Whether residents can carry a concealed firearm without a permit",
    source: "NRA-ILA / Giffords Law Center",
    stateValues: {
      AL: "Permitless Carry", AK: "Permitless Carry", AZ: "Permitless Carry", AR: "Permitless Carry",
      CA: "Permit Required",  CO: "Permit Required",  CT: "Permit Required",  DE: "Permit Required",
      FL: "Permitless Carry", GA: "Permitless Carry", HI: "Permit Required",  ID: "Permitless Carry",
      IL: "Permit Required",  IN: "Permitless Carry", IA: "Permitless Carry", KS: "Permitless Carry",
      KY: "Permitless Carry", LA: "Permitless Carry", ME: "Permitless Carry", MD: "Permit Required",
      MA: "Permit Required",  MI: "Permit Required",  MN: "Permit Required",  MS: "Permitless Carry",
      MO: "Permitless Carry", MT: "Permitless Carry", NE: "Permitless Carry", NV: "Permit Required",
      NH: "Permitless Carry", NJ: "Permit Required",  NM: "Permit Required",  NY: "Permit Required",
      NC: "Permit Required",  ND: "Permitless Carry", OH: "Permitless Carry", OK: "Permitless Carry",
      OR: "Permit Required",  PA: "Permit Required",  RI: "Permit Required",  SC: "Permitless Carry",
      SD: "Permitless Carry", TN: "Permitless Carry", TX: "Permitless Carry", UT: "Permitless Carry",
      VT: "Permitless Carry", VA: "Permit Required",  WA: "Permit Required",  WV: "Permitless Carry",
      WI: "Permit Required",  WY: "Permitless Carry", DC: "Permit Required",
    },
  },
  {
    id: "red_flag",
    category: "Gun Laws",
    icon: "🚩",
    name: "Red Flag / ERPO Law",
    description: "Whether the state has an Extreme Risk Protection Order (red flag) law",
    source: "Giffords Law Center",
    stateValues: {
      AL: "No",  AK: "No",  AZ: "No",  AR: "No",
      CA: "Yes", CO: "Yes", CT: "Yes", DE: "Yes",
      FL: "Yes", GA: "No",  HI: "Yes", ID: "No",
      IL: "Yes", IN: "No",  IA: "No",  KS: "No",
      KY: "No",  LA: "No",  ME: "Yes", MD: "Yes",
      MA: "Yes", MI: "Yes", MN: "Yes", MS: "No",
      MO: "No",  MT: "No",  NE: "No",  NV: "Yes",
      NH: "No",  NJ: "Yes", NM: "Yes", NY: "Yes",
      NC: "No",  ND: "No",  OH: "No",  OK: "No",
      OR: "Yes", PA: "No",  RI: "Yes", SC: "No",
      SD: "No",  TN: "No",  TX: "No",  UT: "Yes",
      VT: "Yes", VA: "Yes", WA: "Yes", WV: "No",
      WI: "No",  WY: "No",  DC: "Yes",
    },
  },
  {
    id: "medicaid_expansion",
    category: "Healthcare",
    icon: "🏥",
    name: "Medicaid Expansion (ACA)",
    description: "Whether the state expanded Medicaid under the Affordable Care Act",
    source: "KFF Health System Tracker",
    stateValues: {
      AL: "Not Expanded", AK: "Expanded",     AZ: "Expanded",     AR: "Expanded",
      CA: "Expanded",     CO: "Expanded",     CT: "Expanded",     DE: "Expanded",
      FL: "Not Expanded", GA: "Expanded",     HI: "Expanded",     ID: "Expanded",
      IL: "Expanded",     IN: "Expanded",     IA: "Expanded",     KS: "Not Expanded",
      KY: "Expanded",     LA: "Expanded",     ME: "Expanded",     MD: "Expanded",
      MA: "Expanded",     MI: "Expanded",     MN: "Expanded",     MS: "Not Expanded",
      MO: "Expanded",     MT: "Expanded",     NE: "Expanded",     NV: "Expanded",
      NH: "Expanded",     NJ: "Expanded",     NM: "Expanded",     NY: "Expanded",
      NC: "Expanded",     ND: "Expanded",     OH: "Expanded",     OK: "Expanded",
      OR: "Expanded",     PA: "Expanded",     RI: "Expanded",     SC: "Not Expanded",
      SD: "Expanded",     TN: "Not Expanded", TX: "Not Expanded", UT: "Expanded",
      VT: "Expanded",     VA: "Expanded",     WA: "Expanded",     WV: "Expanded",
      WI: "Not Expanded", WY: "Not Expanded", DC: "Expanded",
    },
  },
  {
    id: "abortion_access",
    category: "Civil Rights",
    icon: "⚕️",
    name: "Abortion Access",
    description: "General legal status of abortion access (post-Dobbs, approximate 2024)",
    source: "Guttmacher Institute / KFF",
    stateValues: {
      AL: "Banned",              AK: "Protected",           AZ: "Available / Limited",  AR: "Banned",
      CA: "Protected",           CO: "Protected",           CT: "Protected",            DE: "Protected",
      FL: "Available / Limited", GA: "Available / Limited", HI: "Protected",            ID: "Banned",
      IL: "Protected",           IN: "Banned",              IA: "Available / Limited",  KS: "Available / Limited",
      KY: "Banned",              LA: "Banned",              ME: "Protected",            MD: "Protected",
      MA: "Protected",           MI: "Protected",           MN: "Protected",            MS: "Banned",
      MO: "Banned",              MT: "Available / Limited", NE: "Available / Limited",  NV: "Protected",
      NH: "Available / Limited", NJ: "Protected",           NM: "Protected",            NY: "Protected",
      NC: "Available / Limited", ND: "Banned",              OH: "Protected",            OK: "Banned",
      OR: "Protected",           PA: "Available / Limited", RI: "Protected",            SC: "Available / Limited",
      SD: "Banned",              TN: "Banned",              TX: "Banned",               UT: "Severely Restricted",
      VT: "Protected",           VA: "Available / Limited", WA: "Protected",            WV: "Banned",
      WI: "Available / Limited", WY: "Banned",              DC: "Protected",
    },
  },
  {
    id: "voter_id",
    category: "Voting",
    icon: "🗳️",
    name: "Voter ID Requirement",
    description: "Strictness of voter identification laws at the polls",
    source: "NCSL Voter ID Laws database",
    stateValues: {
      AL: "Strict Photo ID",  AK: "Non-Strict ID",   AZ: "Strict Photo ID",  AR: "Strict Photo ID",
      CA: "None Required",    CO: "None Required",   CT: "None Required",    DE: "None Required",
      FL: "Strict Photo ID",  GA: "Strict Photo ID", HI: "Non-Strict ID",    ID: "Non-Strict ID",
      IL: "None Required",    IN: "Strict Photo ID", IA: "Non-Strict ID",    KS: "Non-Strict ID",
      KY: "Non-Strict ID",    LA: "Strict Photo ID", ME: "None Required",    MD: "None Required",
      MA: "None Required",    MI: "Non-Strict ID",   MN: "None Required",    MS: "Strict Photo ID",
      MO: "Strict Photo ID",  MT: "Non-Strict ID",   NE: "Non-Strict ID",    NV: "Non-Strict ID",
      NH: "Non-Strict ID",    NJ: "None Required",   NM: "None Required",    NY: "None Required",
      NC: "Strict Photo ID",  ND: "Strict Photo ID", OH: "Non-Strict ID",    OK: "Strict Photo ID",
      OR: "None Required",    PA: "Non-Strict ID",   RI: "Non-Strict ID",    SC: "Strict Photo ID",
      SD: "Non-Strict ID",    TN: "Strict Photo ID", TX: "Strict Photo ID",  UT: "Non-Strict ID",
      VT: "None Required",    VA: "Strict Photo ID", WA: "None Required",    WV: "Non-Strict ID",
      WI: "Strict Photo ID",  WY: "Non-Strict ID",   DC: "None Required",
    },
  },
  {
    id: "income_tax",
    category: "Economic",
    icon: "📊",
    name: "State Income Tax",
    description: "Structure of state personal income tax",
    source: "Tax Foundation",
    stateValues: {
      AL: "Graduated",  AK: "None",       AZ: "Flat Rate",  AR: "Graduated",
      CA: "Graduated",  CO: "Flat Rate",  CT: "Graduated",  DE: "Graduated",
      FL: "None",       GA: "Flat Rate",  HI: "Graduated",  ID: "Flat Rate",
      IL: "Flat Rate",  IN: "Flat Rate",  IA: "Flat Rate",  KS: "Graduated",
      KY: "Flat Rate",  LA: "Graduated",  ME: "Graduated",  MD: "Graduated",
      MA: "Flat Rate",  MI: "Flat Rate",  MN: "Graduated",  MS: "Graduated",
      MO: "Graduated",  MT: "Graduated",  NE: "Graduated",  NV: "None",
      NH: "None",       NJ: "Graduated",  NM: "Graduated",  NY: "Graduated",
      NC: "Flat Rate",  ND: "Graduated",  OH: "Graduated",  OK: "Graduated",
      OR: "Graduated",  PA: "Flat Rate",  RI: "Graduated",  SC: "Graduated",
      SD: "None",       TN: "None",       TX: "None",       UT: "Flat Rate",
      VT: "Graduated",  VA: "Graduated",  WA: "None",       WV: "Graduated",
      WI: "Graduated",  WY: "None",       DC: "Graduated",
    },
  },
  {
    id: "stand_your_ground",
    category: "Criminal Justice",
    icon: "🛡️",
    name: "Stand Your Ground Law",
    description: "No duty to retreat before using force in self-defense outside the home",
    source: "Everytown / NCSL",
    stateValues: {
      AL: "Yes", AK: "Yes", AZ: "Yes", AR: "Yes",
      CA: "No",  CO: "Yes", CT: "No",  DE: "No",
      FL: "Yes", GA: "Yes", HI: "No",  ID: "Yes",
      IL: "No",  IN: "Yes", IA: "Yes", KS: "Yes",
      KY: "Yes", LA: "Yes", ME: "No",  MD: "No",
      MA: "No",  MI: "Yes", MN: "No",  MS: "Yes",
      MO: "Yes", MT: "Yes", NE: "No",  NV: "Yes",
      NH: "Yes", NJ: "No",  NM: "No",  NY: "No",
      NC: "Yes", ND: "Yes", OH: "Yes", OK: "Yes",
      OR: "No",  PA: "Yes", RI: "No",  SC: "Yes",
      SD: "Yes", TN: "Yes", TX: "Yes", UT: "Yes",
      VT: "No",  VA: "No",  WA: "No",  WV: "Yes",
      WI: "Yes", WY: "Yes", DC: "No",
    },
  },
  {
    id: "right_to_work",
    category: "Economic",
    icon: "🏭",
    name: "Right-to-Work Law",
    description: "Prohibits requiring union membership as a condition of employment",
    source: "NLRB / National Right to Work Legal Defense Foundation",
    stateValues: {
      AL: "Yes", AK: "Yes", AZ: "Yes", AR: "Yes",
      CA: "No",  CO: "No",  CT: "No",  DE: "No",
      FL: "Yes", GA: "Yes", HI: "No",  ID: "Yes",
      IL: "No",  IN: "Yes", IA: "Yes", KS: "Yes",
      KY: "Yes", LA: "Yes", ME: "No",  MD: "No",
      MA: "No",  MI: "No",  MN: "No",  MS: "Yes",
      MO: "No",  MT: "No",  NE: "Yes", NV: "Yes",
      NH: "No",  NJ: "No",  NM: "No",  NY: "No",
      NC: "Yes", ND: "Yes", OH: "No",  OK: "Yes",
      OR: "No",  PA: "No",  RI: "No",  SC: "Yes",
      SD: "Yes", TN: "Yes", TX: "Yes", UT: "Yes",
      VT: "No",  VA: "Yes", WA: "No",  WV: "Yes",
      WI: "Yes", WY: "Yes", DC: "No",
    },
  },
  {
    id: "medical_aid_dying",
    category: "Healthcare",
    icon: "🕊️",
    name: "Medical Aid in Dying",
    description: "Allows terminally ill adults to request life-ending medication from a physician",
    source: "Death with Dignity National Center",
    stateValues: {
      AL: "Not Authorized", AK: "Not Authorized", AZ: "Not Authorized", AR: "Not Authorized",
      CA: "Authorized",     CO: "Authorized",     CT: "Not Authorized", DE: "Not Authorized",
      FL: "Not Authorized", GA: "Not Authorized", HI: "Authorized",     ID: "Not Authorized",
      IL: "Not Authorized", IN: "Not Authorized", IA: "Not Authorized", KS: "Not Authorized",
      KY: "Not Authorized", LA: "Not Authorized", ME: "Authorized",     MD: "Authorized",
      MA: "Authorized",     MI: "Not Authorized", MN: "Authorized",     MS: "Not Authorized",
      MO: "Not Authorized", MT: "Authorized",     NE: "Not Authorized", NV: "Authorized",
      NH: "Not Authorized", NJ: "Authorized",     NM: "Authorized",     NY: "Not Authorized",
      NC: "Not Authorized", ND: "Not Authorized", OH: "Not Authorized", OK: "Not Authorized",
      OR: "Authorized",     PA: "Not Authorized", RI: "Not Authorized", SC: "Not Authorized",
      SD: "Not Authorized", TN: "Not Authorized", TX: "Not Authorized", UT: "Not Authorized",
      VT: "Authorized",     VA: "Not Authorized", WA: "Authorized",     WV: "Not Authorized",
      WI: "Not Authorized", WY: "Not Authorized", DC: "Authorized",
    },
  },
  {
    id: "sports_betting",
    category: "Economic",
    icon: "🎲",
    name: "Sports Betting",
    description: "Legal status of sports wagering",
    source: "American Gaming Association",
    stateValues: {
      AL: "Illegal",        AK: "Illegal",        AZ: "Legal & Active",   AR: "Legal & Active",
      CA: "Illegal",        CO: "Legal & Active", CT: "Legal & Active",   DE: "Legal & Active",
      FL: "Legal & Active", GA: "Illegal",        HI: "Illegal",          ID: "Illegal",
      IL: "Legal & Active", IN: "Legal & Active", IA: "Legal & Active",   KS: "Legal & Active",
      KY: "Legal & Active", LA: "Legal & Active", ME: "Legal & Active",   MD: "Legal & Active",
      MA: "Legal & Active", MI: "Legal & Active", MN: "Illegal",          MS: "Legal / Pending",
      MO: "Legal / Pending",MT: "Legal & Active", NE: "Legal / Pending",  NV: "Legal & Active",
      NH: "Legal & Active", NJ: "Legal & Active", NM: "Legal & Active",   NY: "Legal & Active",
      NC: "Legal & Active", ND: "Illegal",        OH: "Legal & Active",   OK: "Illegal",
      OR: "Legal & Active", PA: "Legal & Active", RI: "Legal & Active",   SC: "Illegal",
      SD: "Legal & Active", TN: "Legal & Active", TX: "Illegal",          UT: "Illegal",
      VT: "Legal & Active", VA: "Legal & Active", WA: "Legal & Active",   WV: "Legal & Active",
      WI: "Legal / Pending",WY: "Legal & Active", DC: "Legal & Active",
    },
  },
];

const CATEGORIES = [...new Set(LAWS.map(l => l.category))];
