import { PrismaClient } from "@prisma/client";
import { normalizeIngredient } from "../lib/ingredients";

const prisma = new PrismaClient();

type SeedRecipe = {
  title: string;
  description: string;
  cuisine: string;
  mealType: "breakfast" | "lunch" | "dinner" | "dessert" | "snack" | "basics";
  prepMinutes: number;
  cookMinutes: number;
  servings: number;
  fromScratch?: boolean;
  verified?: boolean;
  featured?: boolean;
  author?: string;
  ingredients: string[];
  steps: string[];
};

const RECIPES: SeedRecipe[] = [
  {
    title: "Classic Buttermilk Pancakes",
    description: "Fluffy stack with crisp edges. The diner standard, done right at home.",
    cuisine: "American",
    mealType: "breakfast",
    prepMinutes: 10,
    cookMinutes: 15,
    servings: 4,
    verified: true,
    featured: true,
    ingredients: [
      "2 cups all-purpose flour",
      "2 tbsp sugar",
      "2 tsp baking powder",
      "1/2 tsp baking soda",
      "1/2 tsp salt",
      "2 cups buttermilk",
      "2 large eggs",
      "3 tbsp melted butter",
      "Maple syrup, for serving",
    ],
    steps: [
      "Whisk flour, sugar, baking powder, baking soda, and salt in a large bowl.",
      "In a second bowl, whisk buttermilk, eggs, and melted butter.",
      "Pour wet into dry and stir just until combined — lumps are fine.",
      "Heat a non-stick pan over medium. Ladle 1/3 cup batter per pancake.",
      "Flip when bubbles pop on top and edges look set, about 2 minutes per side.",
      "Stack and serve with butter and maple syrup.",
    ],
  },
  {
    title: "Shakshuka",
    description: "Eggs poached in a smoky tomato-pepper sauce. Cook, scoop, dunk bread.",
    cuisine: "Middle Eastern",
    mealType: "breakfast",
    prepMinutes: 10,
    cookMinutes: 25,
    servings: 4,
    verified: true,
    ingredients: [
      "3 tbsp olive oil",
      "1 yellow onion, diced",
      "1 red bell pepper, diced",
      "4 garlic cloves, minced",
      "2 tsp paprika",
      "1 tsp cumin",
      "1/2 tsp chili flakes",
      "1 28oz can crushed tomatoes",
      "Salt and pepper",
      "6 large eggs",
      "Feta cheese, crumbled",
      "Fresh parsley, chopped",
      "Crusty bread, for serving",
    ],
    steps: [
      "Heat olive oil in a large skillet over medium. Add onion and pepper, cook until soft, 7 minutes.",
      "Stir in garlic, paprika, cumin, and chili flakes. Cook 1 minute until fragrant.",
      "Pour in tomatoes, season with salt and pepper. Simmer 10 minutes until thickened.",
      "Make 6 wells in the sauce and crack an egg into each.",
      "Cover and cook 5–8 minutes until whites are set but yolks still runny.",
      "Top with feta and parsley. Serve straight from the pan with bread.",
    ],
  },
  {
    title: "Avocado Toast with Soft Egg",
    description: "Five minutes, four ingredients, no excuses.",
    cuisine: "Modern",
    mealType: "breakfast",
    prepMinutes: 5,
    cookMinutes: 5,
    servings: 1,
    ingredients: [
      "1 thick slice sourdough bread",
      "1 ripe avocado",
      "1 large egg",
      "Lemon juice",
      "Salt and pepper",
      "Chili flakes",
    ],
    steps: [
      "Toast the bread until deeply golden.",
      "Mash avocado with a squeeze of lemon, salt, and pepper.",
      "Fry egg in a little oil, sunny-side up, until whites are set.",
      "Spread avocado on toast, slide egg on top, finish with chili flakes.",
    ],
  },
  {
    title: "Spaghetti Carbonara",
    description: "Roman classic. Eggs, cheese, pork, pepper. No cream — ever.",
    cuisine: "Italian",
    mealType: "dinner",
    prepMinutes: 5,
    cookMinutes: 15,
    servings: 4,
    verified: true,
    featured: true,
    ingredients: [
      "1 lb spaghetti",
      "6 oz guanciale, diced",
      "4 large egg yolks",
      "1 whole egg",
      "1 cup grated Pecorino Romano",
      "1 tsp black pepper, coarsely ground",
      "Salt",
    ],
    steps: [
      "Boil pasta in heavily salted water until 1 minute shy of al dente. Reserve 1 cup pasta water.",
      "Render guanciale in a cold dry pan over medium heat until crisp, about 8 minutes. Kill the heat.",
      "Whisk yolks, whole egg, Pecorino, and pepper in a bowl until paste-like.",
      "Add drained pasta to the guanciale pan. Toss with a splash of pasta water.",
      "Off heat, pour in egg mixture and toss vigorously, adding water until silky.",
      "Plate immediately with extra Pecorino and pepper.",
    ],
  },
  {
    title: "Chicken Tikka Masala",
    description: "Charred yogurt-marinated chicken in a creamy spiced tomato sauce.",
    cuisine: "Indian",
    mealType: "dinner",
    prepMinutes: 30,
    cookMinutes: 40,
    servings: 4,
    verified: true,
    featured: true,
    ingredients: [
      "1.5 lb boneless chicken thighs, cubed",
      "1 cup plain yogurt",
      "2 tbsp lemon juice",
      "2 tbsp garam masala",
      "2 tsp turmeric",
      "2 tsp cumin",
      "1 tsp paprika",
      "4 garlic cloves, minced",
      "2 tbsp grated ginger",
      "3 tbsp butter",
      "1 onion, finely chopped",
      "1 28oz can crushed tomatoes",
      "1 cup heavy cream",
      "Salt",
      "Cilantro, chopped",
      "Basmati rice, for serving",
    ],
    steps: [
      "Mix yogurt, lemon juice, half the spices, half the garlic, and half the ginger. Marinate chicken 30 minutes (or overnight).",
      "Skewer or spread chicken on a sheet pan and broil 8–10 minutes until charred at the edges.",
      "Melt butter in a pot. Cook onion until soft, then add remaining garlic, ginger, and spices. Bloom 1 minute.",
      "Add tomatoes and a pinch of salt. Simmer 15 minutes, then blend smooth.",
      "Stir in cream and the broiled chicken. Simmer 10 minutes.",
      "Top with cilantro and serve over basmati rice.",
    ],
  },
  {
    title: "Beef Tacos al Pastor",
    description: "Pineapple-pork-style marinade, but for beef. Fast weeknight version.",
    cuisine: "Mexican",
    mealType: "dinner",
    prepMinutes: 15,
    cookMinutes: 15,
    servings: 4,
    ingredients: [
      "1 lb beef skirt steak, thinly sliced",
      "3 dried guajillo chiles",
      "1/2 cup pineapple chunks",
      "3 garlic cloves",
      "1 tbsp apple cider vinegar",
      "1 tsp cumin",
      "1 tsp oregano",
      "12 corn tortillas",
      "1 white onion, diced",
      "Cilantro, chopped",
      "Lime wedges",
      "Salt",
    ],
    steps: [
      "Toast guajillos in a dry pan 30 seconds per side, then soak in hot water 10 minutes.",
      "Blend chiles, pineapple, garlic, vinegar, cumin, oregano, and salt into a paste.",
      "Toss beef with marinade and rest 15 minutes.",
      "Sear beef in a screaming-hot pan in batches, 90 seconds total per batch.",
      "Warm tortillas. Fill with beef, onion, cilantro, and a squeeze of lime.",
    ],
  },
  {
    title: "Pho Bo",
    description: "Vietnamese beef noodle soup. The broth is the whole point.",
    cuisine: "Vietnamese",
    mealType: "dinner",
    prepMinutes: 20,
    cookMinutes: 240,
    servings: 6,
    verified: true,
    ingredients: [
      "3 lb beef bones",
      "1 lb beef brisket",
      "1 onion, halved",
      "4 inch piece ginger, halved",
      "4 star anise",
      "1 cinnamon stick",
      "6 cloves",
      "1 tbsp coriander seeds",
      "3 tbsp fish sauce",
      "1 tbsp sugar",
      "Salt",
      "1 lb rice noodles",
      "1/2 lb thinly sliced beef sirloin",
      "Bean sprouts, basil, lime, jalapeño, hoisin, sriracha",
    ],
    steps: [
      "Char onion and ginger directly over a flame or under a broiler until blackened.",
      "Blanch bones and brisket 5 minutes, drain, rinse — this gives a clear broth.",
      "Toast spices in a dry pan 1 minute, then tie in cheesecloth.",
      "Combine bones, brisket, onion, ginger, spice bag, and 4 quarts water. Simmer 3–4 hours.",
      "Pull brisket after 90 minutes, slice thin. Strain broth, season with fish sauce, sugar, salt.",
      "Cook noodles. Place in bowls with raw sirloin and brisket, ladle boiling broth over to cook the beef.",
      "Serve with herbs, lime, chiles, and sauces.",
    ],
  },
  {
    title: "Pad Thai",
    description: "Stir-fried rice noodles with tamarind, peanuts, and lime. Hot and fast.",
    cuisine: "Thai",
    mealType: "dinner",
    prepMinutes: 20,
    cookMinutes: 10,
    servings: 2,
    verified: true,
    ingredients: [
      "8 oz rice noodles",
      "3 tbsp tamarind paste",
      "3 tbsp fish sauce",
      "3 tbsp palm sugar",
      "2 tbsp vegetable oil",
      "2 garlic cloves, minced",
      "8 oz shrimp or chicken",
      "2 eggs",
      "1 cup bean sprouts",
      "3 scallions, chopped",
      "1/4 cup roasted peanuts, crushed",
      "Lime wedges",
      "Cilantro",
    ],
    steps: [
      "Soak rice noodles in warm water 20 minutes until pliable. Drain.",
      "Whisk tamarind, fish sauce, and palm sugar.",
      "Heat oil in a wok over high. Cook garlic 10 seconds, add protein, sear until just cooked.",
      "Push to the side, crack in eggs, scramble, then mix.",
      "Add noodles and sauce, toss until noodles are tender and sauce coats everything.",
      "Toss in sprouts and scallions, plate with peanuts, lime, and cilantro.",
    ],
  },
  {
    title: "Coq au Vin",
    description: "Chicken braised in red wine with lardons, mushrooms, and pearl onions.",
    cuisine: "French",
    mealType: "dinner",
    prepMinutes: 20,
    cookMinutes: 90,
    servings: 6,
    verified: true,
    featured: true,
    ingredients: [
      "1 whole chicken, cut into 8 pieces",
      "6 oz bacon, diced",
      "1 bottle red wine (Burgundy)",
      "2 cups chicken stock",
      "1 onion, diced",
      "2 carrots, diced",
      "4 garlic cloves, minced",
      "8 oz mushrooms, quartered",
      "1 cup pearl onions",
      "2 tbsp tomato paste",
      "2 tbsp flour",
      "Bouquet garni (thyme, parsley, bay leaf)",
      "Salt and pepper",
      "Butter",
    ],
    steps: [
      "Render bacon in a Dutch oven, remove with a slotted spoon. Brown chicken in the fat, remove.",
      "Cook onion and carrot in remaining fat 5 minutes, add garlic and tomato paste, cook 1 minute.",
      "Sprinkle in flour, stir, then deglaze with wine. Add stock, bouquet garni, chicken, and bacon.",
      "Simmer covered 45 minutes until chicken is tender.",
      "Sauté mushrooms and pearl onions in butter until golden. Add to the pot the last 10 minutes.",
      "Adjust seasoning. Serve with crusty bread or buttered noodles.",
    ],
  },
  {
    title: "Chicken Adobo",
    description: "The unofficial national dish of the Philippines. Vinegar, soy, garlic, bay.",
    cuisine: "Filipino",
    mealType: "dinner",
    prepMinutes: 5,
    cookMinutes: 45,
    servings: 4,
    ingredients: [
      "2 lb bone-in chicken thighs",
      "1/2 cup soy sauce",
      "1/2 cup white vinegar",
      "1 head garlic, smashed",
      "3 bay leaves",
      "1 tbsp black peppercorns",
      "1 tbsp sugar",
      "1 cup water",
      "Steamed rice, for serving",
    ],
    steps: [
      "Combine everything except rice in a pot. Bring to a boil, then drop to a simmer.",
      "Cook uncovered 35 minutes, turning chicken halfway, until sauce reduces and clings.",
      "Optional: pull chicken out and crisp the skin under a broiler 3 minutes.",
      "Spoon over rice with plenty of sauce.",
    ],
  },
  {
    title: "Caesar Salad",
    description: "Anchovy, garlic, lemon, parmesan. Make the dressing yourself.",
    cuisine: "Italian-American",
    mealType: "lunch",
    prepMinutes: 15,
    cookMinutes: 0,
    servings: 4,
    ingredients: [
      "2 heads romaine lettuce, torn",
      "4 anchovy fillets",
      "2 garlic cloves",
      "1 egg yolk",
      "2 tbsp lemon juice",
      "1 tsp Dijon mustard",
      "1/2 cup olive oil",
      "1/2 cup grated parmesan",
      "1 cup croutons",
      "Black pepper",
    ],
    steps: [
      "Mash anchovies and garlic into a paste with a knife or mortar.",
      "Whisk paste with yolk, lemon juice, and Dijon. Slowly stream in olive oil, whisking, until thick.",
      "Stir in half the parmesan and plenty of pepper.",
      "Toss with romaine and croutons. Top with remaining parmesan.",
    ],
  },
  {
    title: "Caprese Sandwich",
    description: "Tomato, mozzarella, basil, good bread. Don't overthink it.",
    cuisine: "Italian",
    mealType: "lunch",
    prepMinutes: 5,
    cookMinutes: 0,
    servings: 1,
    ingredients: [
      "1 ciabatta roll",
      "3 slices fresh mozzarella",
      "1 ripe tomato, sliced",
      "4 basil leaves",
      "Olive oil",
      "Balsamic vinegar",
      "Salt and pepper",
    ],
    steps: [
      "Split the roll. Drizzle both sides with olive oil.",
      "Layer mozzarella, tomato, and basil. Salt the tomato.",
      "Add a few drops of balsamic, pepper, close, and press gently.",
    ],
  },
  {
    title: "Chocolate Chip Cookies",
    description: "Crisp edges, chewy center. Brown the butter for extra credit.",
    cuisine: "American",
    mealType: "dessert",
    prepMinutes: 15,
    cookMinutes: 12,
    servings: 24,
    verified: true,
    ingredients: [
      "1 cup butter",
      "3/4 cup brown sugar",
      "1/2 cup white sugar",
      "2 large eggs",
      "2 tsp vanilla extract",
      "2 1/4 cups all-purpose flour",
      "1 tsp baking soda",
      "1 tsp salt",
      "2 cups semisweet chocolate chips",
    ],
    steps: [
      "Brown the butter in a saucepan until nutty. Cool 10 minutes.",
      "Whisk butter with sugars. Add eggs and vanilla.",
      "Mix in flour, baking soda, and salt until just combined. Fold in chocolate.",
      "Chill dough 30 minutes (or overnight for deeper flavor).",
      "Scoop balls onto a lined sheet. Bake at 375°F for 11–13 minutes until edges set.",
      "Cool on the pan 5 minutes before moving.",
    ],
  },
  {
    title: "Tiramisu",
    description: "Espresso-soaked ladyfingers layered with mascarpone cream.",
    cuisine: "Italian",
    mealType: "dessert",
    prepMinutes: 30,
    cookMinutes: 0,
    servings: 8,
    verified: true,
    ingredients: [
      "6 large egg yolks",
      "3/4 cup sugar",
      "1 lb mascarpone",
      "1 1/2 cups heavy cream",
      "1 1/2 cups strong espresso, cooled",
      "3 tbsp dark rum or marsala",
      "24 ladyfinger cookies",
      "2 tbsp cocoa powder",
    ],
    steps: [
      "Whisk yolks and sugar over a double boiler until pale and thick, 5 minutes.",
      "Cool, then whisk in mascarpone until smooth.",
      "Whip cream to soft peaks and fold into the mascarpone mix.",
      "Combine espresso and rum. Dip ladyfingers briefly — don't soak.",
      "Layer half the ladyfingers in a dish, half the cream, repeat.",
      "Dust with cocoa. Refrigerate at least 6 hours, ideally overnight.",
    ],
  },
  {
    title: "Crème Brûlée",
    description: "Cold custard, hot sugar crust. The crack is the reward.",
    cuisine: "French",
    mealType: "dessert",
    prepMinutes: 15,
    cookMinutes: 45,
    servings: 4,
    featured: true,
    ingredients: [
      "2 cups heavy cream",
      "1 vanilla bean, split (or 1 tbsp extract)",
      "5 egg yolks",
      "1/2 cup sugar, plus more for topping",
      "Pinch salt",
    ],
    steps: [
      "Heat cream and vanilla until just steaming. Steep 15 minutes.",
      "Whisk yolks, sugar, and salt. Slowly stream in warm cream while whisking.",
      "Strain into ramekins. Place in a baking dish, pour hot water halfway up the sides.",
      "Bake at 325°F for 35–45 minutes until just set with a slight jiggle in the center.",
      "Chill at least 4 hours.",
      "Sprinkle a thin even layer of sugar on top. Torch until amber and crackling.",
    ],
  },
  {
    title: "Sourdough Bread",
    description: "Naturally leavened loaf. The patient bread.",
    cuisine: "From Scratch",
    mealType: "basics",
    prepMinutes: 30,
    cookMinutes: 45,
    servings: 1,
    fromScratch: true,
    verified: true,
    featured: true,
    ingredients: [
      "500 g bread flour",
      "350 g water",
      "100 g active sourdough starter",
      "10 g salt",
    ],
    steps: [
      "Mix flour and water until no dry spots remain. Rest 1 hour (autolyse).",
      "Add starter and salt. Pinch and fold to incorporate.",
      "Bulk ferment 4–6 hours at room temp, doing 4 stretch-and-folds in the first 2 hours.",
      "Shape into a tight boule. Place seam-up in a floured banneton.",
      "Cold proof in the fridge 12–16 hours.",
      "Preheat Dutch oven at 500°F. Score loaf, bake covered 20 minutes, uncovered 25 minutes at 450°F.",
      "Cool fully on a rack before cutting — at least 1 hour.",
    ],
  },
  {
    title: "Fresh Pasta Dough",
    description: "Eggs and flour. That's it. The base of every great Italian meal.",
    cuisine: "Italian",
    mealType: "basics",
    prepMinutes: 15,
    cookMinutes: 3,
    servings: 4,
    fromScratch: true,
    verified: true,
    ingredients: [
      "2 cups 00 flour",
      "3 large eggs",
      "1 tbsp olive oil",
      "Pinch salt",
    ],
    steps: [
      "Mound flour on a clean surface, make a well in the center.",
      "Crack eggs into the well, add oil and salt. Whisk eggs with a fork, gradually pulling in flour.",
      "Once shaggy, knead 10 minutes until smooth and elastic.",
      "Wrap and rest 30 minutes.",
      "Roll thin with a pin or pasta machine, cut to desired shape.",
      "Cook in salted boiling water 2–3 minutes until it floats.",
    ],
  },
  {
    title: "Pizza Dough",
    description: "One bowl, one rise, Saturday-night ready.",
    cuisine: "Italian",
    mealType: "basics",
    prepMinutes: 15,
    cookMinutes: 0,
    servings: 4,
    fromScratch: true,
    ingredients: [
      "500 g bread flour",
      "325 g warm water",
      "10 g salt",
      "2 g instant yeast",
      "1 tbsp olive oil",
    ],
    steps: [
      "Mix everything in a bowl until shaggy. Rest 20 minutes.",
      "Knead in the bowl 5 minutes until smooth.",
      "Cover and rise at room temp 4–6 hours, or fridge overnight.",
      "Divide into 4 balls. Rest 30 minutes covered before stretching.",
      "Stretch by hand, top, and bake on a hot stone or steel at 500°F for 6–8 minutes.",
    ],
  },
];

async function main() {
  console.log("Clearing existing data…");
  await prisma.cookbookRecipe.deleteMany();
  await prisma.recipeIngredient.deleteMany();
  await prisma.recipe.deleteMany();
  await prisma.cookbook.deleteMany();

  console.log(`Seeding ${RECIPES.length} recipes…`);
  for (const r of RECIPES) {
    await prisma.recipe.create({
      data: {
        title: r.title,
        description: r.description,
        cuisine: r.cuisine,
        mealType: r.mealType,
        prepMinutes: r.prepMinutes,
        cookMinutes: r.cookMinutes,
        servings: r.servings,
        steps: JSON.stringify(r.steps),
        fromScratch: r.fromScratch ?? false,
        verified: r.verified ?? false,
        featured: r.featured ?? false,
        author: r.author ?? "Cookbook Kitchen",
        ingredients: {
          create: r.ingredients.map((display) => ({
            display,
            name: normalizeIngredient(display),
          })),
        },
      },
    });
  }

  console.log("Creating starter cookbooks…");
  const allRecipes = await prisma.recipe.findMany();
  const featured = allRecipes.filter((r) => r.featured);
  const fromScratch = allRecipes.filter((r) => r.fromScratch);

  await prisma.cookbook.create({
    data: {
      name: "House Favorites",
      description: "The handful we cook on repeat.",
      author: "Cookbook Kitchen",
      recipes: {
        create: featured.map((r) => ({ recipeId: r.id })),
      },
    },
  });

  await prisma.cookbook.create({
    data: {
      name: "From Scratch",
      description: "Doughs, broths, and bases worth making yourself.",
      author: "Cookbook Kitchen",
      recipes: {
        create: fromScratch.map((r) => ({ recipeId: r.id })),
      },
    },
  });

  console.log("Done.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
